### ISSUE TITLE
Problem with " glyph in Fira display

### ISSUE THREAD

**Issue by Manuel-K** [mozilla/mozilla.github.io#6]
I'm not sure if this is the right place, but there is something wrong with the " glyph in all weights of Fira except Regular on http://mozilla.github.io/Fira/

The '" of the sample text are overlapping. The " doesn't seem to have the necessary width.

The problem doesn't occur when using the version from the FiraFonts4004.zip archive.

It's nothing major, but I think it's a bad that this happens in a showcase page.

**Comment by Osmose** [comment]
I believe the repo you're looking for is https://github.com/mozilla/Fira, and the crux of the issue seems to be that the `gh-pages` branch doesn't have the latest version of the font. If you file an issue on that repo asking about it they should be able to update that branch with the latest release.

Thanks for filing the issue!

**Comment by Manuel-K** [comment]
You're right. Thanks.
